---
name: Feature request
description: Suggest an idea for Codex Helper
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your idea! Please answer the questions below so we can understand the problem and desired solution.
  - type: textarea
    id: problem
    attributes:
      label: Problem description
      description: What pain point or use case would this feature address?
      placeholder: It's hard to ...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: If you have something in mind, outline it here. Mockups and code snippets welcome.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds you've tried?
  - type: textarea
    id: notes
    attributes:
      label: Additional context
      description: Anything else we should know (screenshots, related issues, etc.)?
